In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [6]:
x = 1

In [7]:
a = np.array([x])
a

array([1])

In [8]:
a = np.array([1, 2 ,3, 4, 5])
b = np.array([2, 3, 4, 5, 6])

In [9]:
a + b

array([ 3,  5,  7,  9, 11])

In [10]:
a + x

array([2, 3, 4, 5, 6])

In [12]:
a * b

array([ 2,  6, 12, 20, 30])

In [21]:
dot = np.dot(a, b)
dot

70

In [18]:
m = np.array([[1, 2], [0, -1], [3, 4], [5, 6], [7, 8]])

In [19]:
dot = np.dot(a, m)
dot

array([65, 76])

In [22]:
import numpy as np


def make_array_from_list(some_list):
    return np.array(some_list)


def make_array_from_number(num):
    return np.array([num])


class NumpyBasics:
    def add_arrays(self, a, b):
        return a + b

    def add_array_number(self, a, num):
        return a + num

    def multiply_elementwise_arrays(self, a, b):
        return a * b

    def dot_product_arrays(self, a, b):
        return np.dot(a, b)

    def dot_1d_array_2d_array(self, a, m):
        # consider the 2d array to be like a matrix
        return np.dot(a, m)

In [23]:
make_array_from_list([1, 2])

array([1, 2])

In [25]:
make_array_from_number(1)

array([1])

In [26]:
nb = NumpyBasics()

In [27]:
nb.add_arrays(a, b)

array([ 3,  5,  7,  9, 11])

In [28]:
nb.add_array_number(a, 5)

array([ 6,  7,  8,  9, 10])

In [29]:
nb.multiply_elementwise_arrays(a, b)

array([ 2,  6, 12, 20, 30])

In [30]:
nb.dot_product_arrays(a, b)

70

In [31]:
nb.dot_1d_array_2d_array(b, m)

array([81, 95])